CREATE MATERIALIZED VIEW IF NOT EXISTS materialize_view_cultivation.cultivation TO cultivation.cultivation
AS
SELECT
    coalesce(JSONExtractInt(message, 'after', 'id'), JSONExtractInt(message, 'before', 'id')) AS id,
    JSONExtractInt(message, 'after', 'pond_id') AS pond_id,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'periode_siklus'), JSONExtractInt(message, 'after', 'periode_siklus'), NULL) AS periode_siklus,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'perkiran_doc'), JSONExtractInt(message, 'after', 'perkiran_doc'), NULL) AS perkiran_doc,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'cultivation_preparation_id'), JSONExtractInt(message, 'after', 'cultivation_preparation_id'), NULL) AS cultivation_preparation_id,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'cultivation_seed_id'), JSONExtractInt(message, 'after', 'cultivation_seed_id'), NULL) AS cultivation_seed_id,
    JSONExtractInt(message, 'after', 'status') AS status,
    JSONExtractInt(message, 'after', 'created_by') AS created_by,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'created_at') AND length(JSONExtractString(message, 'after', 'created_at')) > 0, parseDateTime64BestEffort(JSONExtractString(message, 'after', 'created_at')), NULL) AS created_at,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'updated_by'), JSONExtractInt(message, 'after', 'updated_by'), NULL) AS updated_by,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'updated_at') AND length(JSONExtractString(message, 'after', 'updated_at')) > 0, parseDateTime64BestEffort(JSONExtractString(message, 'after', 'updated_at')), NULL) AS updated_at,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'deleted_by'), JSONExtractInt(message, 'after', 'deleted_by'), NULL) AS deleted_by,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'deleted_at') AND length(JSONExtractString(message, 'after', 'deleted_at')) > 0, parseDateTime64BestEffort(JSONExtractString(message, 'after', 'deleted_at')), NULL) AS deleted_at,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'end_doc') AND length(JSONExtractString(message, 'after', 'end_doc')) > 0, parseDateTime64BestEffort(JSONExtractString(message, 'after', 'end_doc')), NULL) AS end_doc,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'start_doc') AND length(JSONExtractString(message, 'after', 'start_doc')) > 0, parseDateTime64BestEffort(JSONExtractString(message, 'after', 'start_doc')), NULL) AS start_doc,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'total_populasi'), JSONExtractFloat(message, 'after', 'total_populasi'), NULL) AS total_populasi,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'abw'), JSONExtractFloat(message, 'after', 'abw'), NULL) AS abw,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'adg'), JSONExtractFloat(message, 'after', 'adg'), NULL) AS adg,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'biomassa'), JSONExtractFloat(message, 'after', 'biomassa'), NULL) AS biomassa,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'fcr'), JSONExtractFloat(message, 'after', 'fcr'), NULL) AS fcr,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'sr'), JSONExtractFloat(message, 'after', 'sr'), NULL) AS sr,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'panen_count'), JSONExtractInt(message, 'after', 'panen_count'), NULL) AS panen_count,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'panen_total_populasi'), JSONExtractFloat(message, 'after', 'panen_total_populasi'), NULL) AS panen_total_populasi,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'pemberian_pakan_kumulative'), JSONExtractFloat(message, 'after', 'pemberian_pakan_kumulative'), NULL) AS pemberian_pakan_kumulative,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'total_seed'), JSONExtractFloat(message, 'after', 'total_seed'), NULL) AS total_seed,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'size_avg'), JSONExtractFloat(message, 'after', 'size_avg'), NULL) AS size_avg,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'panen_biomassa'), JSONExtractFloat(message, 'after', 'panen_biomassa'), NULL) AS panen_biomassa,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'panen_sr'), JSONExtractFloat(message, 'after', 'panen_sr'), NULL) AS panen_sr,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'is_cultivation'), JSONExtractInt(message, 'after', 'is_cultivation'), NULL) AS is_cultivation,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'panen_fcr'), JSONExtractFloat(message, 'after', 'panen_fcr'), NULL) AS panen_fcr,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'pemberian_saprotam_kumulative'), JSONExtractFloat(message, 'after', 'pemberian_saprotam_kumulative'), NULL) AS pemberian_saprotam_kumulative,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'seed_density'), JSONExtractFloat(message, 'after', 'seed_density'), NULL) AS seed_density,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'seed_size_akhir'), JSONExtractFloat(message, 'after', 'seed_size_akhir'), NULL) AS seed_size_akhir,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'seed_tonase'), JSONExtractFloat(message, 'after', 'seed_tonase'), NULL) AS seed_tonase,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'seed_total_kantong'), JSONExtractInt(message, 'after', 'seed_total_kantong'), NULL) AS seed_total_kantong,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'batch'), JSONExtractInt(message, 'after', 'batch'), NULL) AS batch,
    if(JSONHas(message, 'after') AND JSONHas(JSONExtractRaw(message, 'after'), 'block_id'), JSONExtractInt(message, 'after', 'block_id'), NULL) AS block_id,
    JSONExtractString(message, 'op') AS op,
    JSONExtractString(message, 'source', 'db') AS db,
    JSONExtractString(message, 'source', 'schema') AS schema,
    JSONExtractString(message, 'source', 'table') AS `table`,
    JSONExtractInt(message, 'source', 'lsn') AS lsn,
    JSONExtractInt(message, 'ts_ms') AS ts_ms,
    JSONExtractInt(message, 'source', 'txId') AS txId,
    _key AS _kafka_key,
    _topic AS _kafka_topic,
    _partition AS _kafka_partition,
    _offset AS _kafka_offset,
    _timestamp AS _kafka_timestamp
FROM kafka_cultivation.cultivation
WHERE JSONHas(message, 'after') OR JSONHas(message, 'before');
